import "reflect-metadata";
import { Container } from "typedi";

import { IUserRepositoryToken } from "../../application/repositories/IUserRepository";
import { UserRepository } from "../repositories/UserRepository";
import { IVerficaitonCodeRepositoryToken } from "../../application/repositories/IVerificaitonCodeRepository";
import { VerificationCodeRepository } from "../repositories/VerficationCodeRepository";
import { ISessionRepositoryToken } from "../../application/repositories/ISessionRepository";
import { SessionRepository } from "../repositories/SessionRepository";
import { IOtpReposirtoryCodeToken } from "../../application/repositories/IOtpReposirtory";
import { OtpRepository } from "../repositories/OtpRepository";
import { IDoctorRepositoryToken } from "../../application/repositories/IDoctorReposirtory";
import { DoctorRepository } from "../repositories/DoctorRepository";
import { IAdminRepositoryToken } from "../../application/repositories/IAdminRepository";
import { AdminRepository } from "../repositories/AdminRepository";
import { INotificationRepositoryToken } from "../../application/repositories/INotificationRepository";
import { NotificationRepository } from "../repositories/NotifcationRepository";
import { ISlotRepositoryToken } from "../../application/repositories/ISlotRepository";
import { SlotRepository } from "../repositories/SlotRepository";
import { IAppointmentRepositoryToken } from "../../application/repositories/IAppointmentRepository";
import { AppointmentRepository } from "../repositories/AppointmentRepository";
import { IWalletRepositoryToken } from "../../application/repositories/IWalletRepository";
import { IChatRepositoryToken } from "../../application/repositories/IChatRepository";
import { ChatRepository } from "../repositories/ChatRepository";
import { IConversationRepositoryToken } from "../../application/repositories/IConversationRepository";
import { ConversationRepository } from "../repositories/ConversationRepository";
import { ICaloriesDetailsRepositoryToken } from "../../application/repositories/ICaloriesDetailsRepository";
import { CaloriesRepository } from "../repositories/CaloriresRepository";
import { IPremiumSubscriptionRepositoryToken } from "../../application/repositories/IPremiumSubscription";
import { PremiumSubscriptionRepository } from "../repositories/PremiumSubscription";
import { ITransactionRepositoryToken } from "../../application/repositories/ITransactionRepository";
import { TransactionRepository } from "../repositories/TransactionRepository";
import { IReviewsRepositoryToken } from "../../application/repositories/IReviewsRepository";
import { ReviewsRepository } from "../repositories/ReviewsRepository";
import { IRatingRepositoryToken } from "../../application/repositories/IRatingsRepository";
import { RatingsRepository } from "../repositories/RatingsRepository";
import WalletRepository from "../repositories/WalletRepository";
import { IUserSubscriptionRepositoryToken } from "../../application/repositories/IUserSubscriptionRepository";
import { UserSubscriptionRepository } from "../repositories/UserSubscription";
import { IAdminUseCaseToken } from "../../application/user-casers/interface/IAdminUseCase";
import { AdminUseCase } from "../../application/user-casers/AdminUseCase";
import { IAppUseCaseToken } from "../../application/user-casers/interface/IAppUseCase";
import { AppUseCase } from "../../application/user-casers/AppUseCase";
import { ICaloriesUseCaseToken } from "../../application/user-casers/interface/ICaloriesUseCase";
import { CaloriesUseCase } from "../../application/user-casers/CaloriesUserCase";
import { IChatUseCaseToken } from "../../application/user-casers/interface/IChatUseCase";
import { ChatUseCase } from "../../application/user-casers/ChatUseCase";
import { IDoctorFeatUseCaseToken } from "../../application/user-casers/interface/IDoctorFeatUseCase";
import { DoctorFeatUseCase } from "../../application/user-casers/DoctorFeatUseCase";
import { IDoctorUseCaseToken } from "../../application/user-casers/interface/IDoctorUseCase";
import { DoctorUseCase } from "../../application/user-casers/DoctorUseCase";
import { IPaymentUseCaseToken } from "../../application/user-casers/interface/IPaymentUseCase";
import { PaymentUseCase } from "../../application/user-casers/PaymentUseCase";
import { IRegisterUseCaseToken } from "../../application/user-casers/interface/IRegisterUseCase";
import { RegisterUserUseCase } from "../../application/user-casers/RegisterUserUseCase";
import { IWebRtcUseCaseToken } from "../../application/user-casers/interface/IWebRtcUseCase";
import { WebRtcUseCase } from "../../application/user-casers/WebRtcUseCase";
import { IAdminControllerToken } from "../../application/repositories/IAdminController";
import { AdminController } from "../../interface/controllers/Admin/AdminController";
import { IAppControllerToken } from "../../application/repositories/IAppController";
import { AppController } from "../../interface/controllers/Feat/AppController";
import { IUserControllerToken } from "../../application/repositories/IUserController";
import { UserController } from "../../interface/controllers/auth/UserController";
import { IDoctorControllerToken } from "../../application/repositories/IDoctorController";
import { DoctorController } from "../../interface/controllers/doctor/DoctorController";
import { IDoctorFeatControllerToken } from "../../application/repositories/IDoctorFeatController";
import { DoctorFeatController } from "../../interface/controllers/doctor/DoctorFeatController";
import { ICaloriesControllerToken } from "../../application/repositories/ICaloriesController";
import { CaloriesController } from "../../interface/controllers/Feat/CaloriesControllle";
import { IChatControllerToken } from "../../application/repositories/IChatController";
import { ChatController } from "../../interface/controllers/Feat/ChatController";
import { IPaymentControllerToken } from "../../application/repositories/IPaymentController";
import { PaymentController } from "../../interface/controllers/Feat/PaymentController";
import { IWebRtcControllerToken } from "../../application/repositories/IWebRtcCotroller";
import { WebRtcController } from "../../interface/controllers/Feat/WebRtcController";

Container.set(IUserRepositoryToken, new UserRepository());
Container.set(IVerficaitonCodeRepositoryToken, new VerificationCodeRepository());
Container.set(ISessionRepositoryToken, new SessionRepository());
Container.set(IOtpReposirtoryCodeToken, new OtpRepository());
Container.set(IDoctorRepositoryToken, new DoctorRepository());
Container.set(IAdminRepositoryToken, new AdminRepository());
Container.set(INotificationRepositoryToken, new NotificationRepository());
Container.set(ISlotRepositoryToken, new SlotRepository());
Container.set(IAppointmentRepositoryToken, new AppointmentRepository());
Container.set(IWalletRepositoryToken, new WalletRepository());
Container.set(IChatRepositoryToken, new ChatRepository());
Container.set(IConversationRepositoryToken, new ConversationRepository());
Container.set(ICaloriesDetailsRepositoryToken, new CaloriesRepository());
Container.set(IPremiumSubscriptionRepositoryToken, new PremiumSubscriptionRepository());
Container.set(ITransactionRepositoryToken, new TransactionRepository());
Container.set(IReviewsRepositoryToken, new ReviewsRepository());
Container.set(IRatingRepositoryToken, new RatingsRepository());
Container.set(IUserSubscriptionRepositoryToken, new UserSubscriptionRepository());



//** controllers**
Container.set(IAdminControllerToken, Container.get(AdminController));
Container.set(IAppControllerToken, Container.get(AppController));
Container.set(IUserControllerToken, Container.get(UserController));
Container.set(IDoctorControllerToken, Container.get(DoctorController));
Container.set(IDoctorFeatControllerToken, Container.get(DoctorFeatController));
Container.set(ICaloriesControllerToken, Container.get(CaloriesController));
Container.set(IChatControllerToken, Container.get(ChatController));
Container.set(IPaymentControllerToken, Container.get(PaymentController));
Container.set(IWebRtcControllerToken, Container.get(WebRtcController));

//**usecases**
Container.set(IAdminUseCaseToken, Container.get(AdminUseCase));
Container.set(IAppUseCaseToken, Container.get(AppUseCase));
Container.set(ICaloriesUseCaseToken, Container.get(CaloriesUseCase));
Container.set(IChatUseCaseToken, Container.get(ChatUseCase));
Container.set(IDoctorFeatUseCaseToken, Container.get(DoctorFeatUseCase));
Container.set(IDoctorUseCaseToken, Container.get(DoctorUseCase));
Container.set(IPaymentUseCaseToken, Container.get(PaymentUseCase));
Container.set(IRegisterUseCaseToken, Container.get(RegisterUserUseCase));
Container.set(IWebRtcUseCaseToken, Container.get(WebRtcUseCase));
